[profile.default]
src = "."
test = "test"
out = "out"
cache_path = "cache"
libs = []
auto_detect_remappings = false
optimizer = false
solc_version = "0.8.30"
evm_version = "shanghai"
fs_permissions = [{ access = "read", path = "out" }]
