[profile.default]
src = "src"
test = "test"
solc = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=/Users/zhanglongqin/AuditHoundV2/cases/alkimiya_io/src/onchain_auto/0xf3f84ce038442ae4c4dcb6a8ca8bacd7f28c9bde/lib/openzeppelin-contracts/contracts/",
    "solady/=/Users/zhanglongqin/AuditHoundV2/cases/alkimiya_io/src/onchain_auto/0xf3f84ce038442ae4c4dcb6a8ca8bacd7f28c9bde/lib/solady/src/",
]
